title: MODERU
name: Aragaki Yui
description: "Photographer's album theme for モデル (Model)"
baseurl: /moderu
links:
  - icon: icon-envelope-o
    link: /
  - icon: icon-wechat
    link: /
  - icon: icon-weibo
    link: /
  - icon: icon-instagram
    link: /
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - moderu.gemspec
  - README.md
